keboola_docker_prepare:
    path:     /prepare
    defaults: { _controller: KeboolaDockerBundle:Api:prepare }
    methods:  [POST]

keboola_docker_component_run:
    path:     /{component}/run
    defaults: { _controller: KeboolaDockerBundle:Api:run }
    methods:  [POST]

