keboola_docker_sandbox:
    path:     /sandbox
    defaults: { _controller: KeboolaDockerBundle:Api:sandbox }
    methods:  [POST]

keboola_docker_component_input:
    path:     /{component}/input
    defaults: { _controller: KeboolaDockerBundle:Api:input }
    methods:  [POST]

keboola_docker_component_run:
    path:     /{component}/run
    defaults: { _controller: KeboolaDockerBundle:Api:run }
    methods:  [POST]

keboola_docker_component_dry_run:
    path:     /{component}/dry-run
    defaults: { _controller: KeboolaDockerBundle:Api:dryRun }
    methods:  [POST]
