language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
notifications:
  email: false
branches:
  only:
  - master
install:
  - composer install --no-scripts
env:
  global:
    secure: KMjTyndS3OXhGR3XQlmonIgnJI1p1Xl1NcRK9oZzoGyyjpCmD8eAhI4UHUS4aki/iveMaokuSxdmDkt0E5AmbDD5rmMzyMo7UMd/tDAH9rVI5IZVbkLcEwB8cntgrg7eBZqzFyzgqze4kKB6me/XjGP0BcON3+kEWjI4Hj1hZHY=
